# Generated by Django 4.1.7 on 2023-04-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='document',
        ),
    ]
